import type { Metadata } from 'next'
import { Archivo_Black } from 'next/font/google'
import './globals.css'

import Navigation from '@/components/navigation/Navigation'

const archivo = Archivo_Black({
	subsets: ['latin'],
	weight: '400',
	variable: '--font-archivo',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${archivo.variable} font-sans antialiased`}>
				<div className='flex justify-between items-center h-screen bg-stone-950'>
					<Navigation />
					<main>{children}</main>
					<footer>Footer</footer>
				</div>
			</body>
		</html>
	)
}
