import type { Metadata } from "next";
import { Archivo_Black } from "next/font/google";
import "./globals.css";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const archivo = Archivo_Black({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${archivo.variable} font-sans antialiased`}>
        <div className="grid h-screen w-full grid-cols-[minmax(200px,15%)_1fr_minmax(250px,20%)] bg-stone-950">
          <Header />
          <main className="w-full overflow-y-auto">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
